- name: mkdir ~/.ssh
  file: path=~/.ssh state=directory

- name: add authorized_keys
  template: src=~/.ssh/id_rsa.pub dest=~/.ssh/authorized_keys

- name: edit sshd_config
  sudo: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp='^# PasswordAuthentication yes' line='PasswordAuthentication no' 

- name: restart sshd daemon
  sudo: yes
  service: name=ssh state=restarted enabled=true

- name: Installs nginx web server
  sudo: yes
  apt: pkg=nginx state=latest
  notify: reload nginx

- name: clone git
  git: repo=git@github.com:ymizushi/dotfiles.git dest=/home/ymizushi/dotfiles update=yes

- name: execute shell command
  command: /bin/bash symbolic_link.bash chdir=/home/ymizushi/dotfiles
